language: ruby
cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - moorer@udel.edu
    on_failure: change
    on_success: never