language: ruby
cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - moorer@udel.edu
    on_failure: always
    on_success: always
